id: I5E6BB27E
legacy_id: P008146
ocr_import_info:
  bdrc_scan_id: W1KG3832
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T07:04:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:17:43.782967+00:00'
last_modified: 2022-08-31 23:17:49.000119
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3832
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3832
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེར་ཕྱིན་གྱི་ལུང་ལ་འཇུག་པའི་སྒོ
  author: འབྲུག་ཆེན ༠༤་པདྨ་དཀར་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8441198304209636
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1KG3895:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3895
      total_pages: 88
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3895.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8441198304209636
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
