id: P008146
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3832
  title: ཤེར་ཕྱིན་གྱི་ལུང་ལ་འཇུག་པའི་སྒོ་
  author: ''
  volumes:
    4921031ce94144f58d140a2f48893bf8:
      image_group_id: I1KG3895
      title: ''
      volume_number: 1
      total_pages: 88
ebook_metadata:
  title: ཤེར་ཕྱིན་གྱི་ལུང་ལ་འཇུག་པའི་སྒོ་
  author: ''
  sku: P008146
  cover: cover.jpg
  layers:
  - pagination
