id: P008146
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:04:29.930975
source_metadata:
  id: bdr:W1KG3832
  title: ཤེར་ཕྱིན་གྱི་ལུང་ལ་འཇུག་པའི་སྒོ་
  author: ''
  volumes:
    df6d0eb2373e434183a3a3b48ce23f9a:
      image_group_id: I1KG3895
      title: Volume 1 of sher phyin gyi lung la 'jug pa'i sgo
      volume_number: 1
      total_pages: 88
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
